### ISSUE TITLE
Option to set interval

### ISSUE THREAD

**Issue by markus138** [Leocardoso94/netflix-skipper#1]
Hello, very handy app! It would be great though if we could override the 3000ms interval from the addons option menu ourselves.

**Comment by Leocardoso94** [comment]
Hi, @markus138 I removed the setInteval implementation, now I'm using the [MutationObserver](https://developer.mozilla.org/pt-BR/docs/Web/API/MutationObserver) to skip the intros, so now it's jumping the intro as soon as the button appears in the DOM .

Would you like more time to skip the intros?

**Comment by markus138** [comment]
no even better ;)
